package com.mockproject.du1.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mockproject.du1.model.Role;
import com.mockproject.du1.model.RoleExample;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	long countByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int deleteByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	List<Role> selectByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	Role selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role
	 * @mbg.generated  Mon Nov 04 21:27:54 ICT 2019
	 */
	int updateByPrimaryKey(Role record);

	/**
	 * 
	 */
	List<Role> sqlGetAllRoleSelect();

	/**
	 * 
	 */
	Role sqlGetRoleByIdSelect(@Param("roleId") int roleId);

	/**
	 * 
	 */
	List<Role> sqlGetRoleByNameOrCodeSelect(@Param("extractCondition") String extractCondition);
	
	/**
	 * 
	 */
	long sqlCountRoleByNameSelect(@Param("roleName") String roleName);
	
	/**
	 * 
	 */
	long sqlCountRoleByCodeSelect(@Param("roleCode") String roleCode);

	/**
	 * 
	 */
	int sqlEditRoleInfoUpdate(Role role);

	/**
	 * 
	 */
	int sqlRoleInsert(Role role);
//    int sqlCreateRoleDetailInsert(int);
}