package com.mockproject.du1.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.mockproject.du1.model.UserDepartment;
import com.mockproject.du1.model.UserDepartmentExample;

public interface UserDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    long countByExample(UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int deleteByExample(UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int insert(UserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int insertSelective(UserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    List<UserDepartment> selectByExample(UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    UserDepartment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int updateByExampleSelective(@Param("record") UserDepartment record, @Param("example") UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int updateByExample(@Param("record") UserDepartment record, @Param("example") UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int updateByPrimaryKeySelective(UserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_department
     *
     * @mbg.generated Mon Nov 04 21:27:54 ICT 2019
     */
    int updateByPrimaryKey(UserDepartment record);
}