package com.mockproject.du1.model;

import java.util.Date;

public class CampaignCustomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.sent_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date sentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date createdTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date updatedTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.campaign_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long campaignId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.customer_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.campaign_customer.user_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.id
	 * @return  the value of public.campaign_customer.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.id
	 * @param id  the value for public.campaign_customer.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.sent_date
	 * @return  the value of public.campaign_customer.sent_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getSentDate() {
		return sentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.sent_date
	 * @param sentDate  the value for public.campaign_customer.sent_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.updated_by
	 * @return  the value of public.campaign_customer.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.updated_by
	 * @param updatedBy  the value for public.campaign_customer.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.created_timestamp
	 * @return  the value of public.campaign_customer.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getCreatedTimestamp() {
		return createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.created_timestamp
	 * @param createdTimestamp  the value for public.campaign_customer.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.updated_timestamp
	 * @return  the value of public.campaign_customer.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getUpdatedTimestamp() {
		return updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.updated_timestamp
	 * @param updatedTimestamp  the value for public.campaign_customer.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.campaign_id
	 * @return  the value of public.campaign_customer.campaign_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getCampaignId() {
		return campaignId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.campaign_id
	 * @param campaignId  the value for public.campaign_customer.campaign_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.customer_id
	 * @return  the value of public.campaign_customer.customer_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.customer_id
	 * @param customerId  the value for public.campaign_customer.customer_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.campaign_customer.user_id
	 * @return  the value of public.campaign_customer.user_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.campaign_customer.user_id
	 * @param userId  the value for public.campaign_customer.user_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}
}