package com.mockproject.du1.model;

import lombok.Builder;

import java.util.Date;
@Builder
public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.id
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.first_name
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.last_name
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.dob
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.email
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.address
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.company
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.is_activated
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private Integer isActivated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.updated_by
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.created_timestamp
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private Date createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.updated_timestamp
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    private Date updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.id
     *
     * @return the value of public.customer.id
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.id
     *
     * @param id the value for public.customer.id
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.first_name
     *
     * @return the value of public.customer.first_name
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.first_name
     *
     * @param firstName the value for public.customer.first_name
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.last_name
     *
     * @return the value of public.customer.last_name
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.last_name
     *
     * @param lastName the value for public.customer.last_name
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.dob
     *
     * @return the value of public.customer.dob
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.dob
     *
     * @param dob the value for public.customer.dob
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setDob(String dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.email
     *
     * @return the value of public.customer.email
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.email
     *
     * @param email the value for public.customer.email
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.address
     *
     * @return the value of public.customer.address
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.address
     *
     * @param address the value for public.customer.address
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.company
     *
     * @return the value of public.customer.company
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.company
     *
     * @param company the value for public.customer.company
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.is_activated
     *
     * @return the value of public.customer.is_activated
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public Integer getIsActivated() {
        return isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.is_activated
     *
     * @param isActivated the value for public.customer.is_activated
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setIsActivated(Integer isActivated) {
        this.isActivated = isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.updated_by
     *
     * @return the value of public.customer.updated_by
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.updated_by
     *
     * @param updatedBy the value for public.customer.updated_by
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.created_timestamp
     *
     * @return the value of public.customer.created_timestamp
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.created_timestamp
     *
     * @param createdTimestamp the value for public.customer.created_timestamp
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.updated_timestamp
     *
     * @return the value of public.customer.updated_timestamp
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.updated_timestamp
     *
     * @param updatedTimestamp the value for public.customer.updated_timestamp
     *
     * @mbggenerated Tue Nov 05 09:11:00 ICT 2019
     */
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
}