package com.mockproject.du1.model;

import java.util.Date;

public class Pages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.code
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.url
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date createdTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.pages.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date updatedTimestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.id
	 * @return  the value of public.pages.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.id
	 * @param id  the value for public.pages.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.name
	 * @return  the value of public.pages.name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.name
	 * @param name  the value for public.pages.name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.code
	 * @return  the value of public.pages.code
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.code
	 * @param code  the value for public.pages.code
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.url
	 * @return  the value of public.pages.url
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.url
	 * @param url  the value for public.pages.url
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.updated_by
	 * @return  the value of public.pages.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.updated_by
	 * @param updatedBy  the value for public.pages.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.created_timestamp
	 * @return  the value of public.pages.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getCreatedTimestamp() {
		return createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.created_timestamp
	 * @param createdTimestamp  the value for public.pages.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.pages.updated_timestamp
	 * @return  the value of public.pages.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getUpdatedTimestamp() {
		return updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.pages.updated_timestamp
	 * @param updatedTimestamp  the value for public.pages.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}
}