package com.mockproject.du1.model;

import java.util.Date;

public class RolePages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role_pages.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role_pages.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role_pages.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String createdTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role_pages.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role_pages.role_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role_pages.pages_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long pagesId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_pages.id
	 * @return  the value of public.role_pages.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_pages.id
	 * @param id  the value for public.role_pages.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_pages.updated_by
	 * @return  the value of public.role_pages.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_pages.updated_by
	 * @param updatedBy  the value for public.role_pages.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_pages.created_timestamp
	 * @return  the value of public.role_pages.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getCreatedTimestamp() {
		return createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_pages.created_timestamp
	 * @param createdTimestamp  the value for public.role_pages.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCreatedTimestamp(String createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_pages.updated_timestamp
	 * @return  the value of public.role_pages.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedTimestamp() {
		return updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_pages.updated_timestamp
	 * @param updatedTimestamp  the value for public.role_pages.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedTimestamp(String updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_pages.role_id
	 * @return  the value of public.role_pages.role_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_pages.role_id
	 * @param roleId  the value for public.role_pages.role_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_pages.pages_id
	 * @return  the value of public.role_pages.pages_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getPagesId() {
		return pagesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_pages.pages_id
	 * @param pagesId  the value for public.role_pages.pages_id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setPagesId(Long pagesId) {
		this.pagesId = pagesId;
	}
}