package com.mockproject.du1.model;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.code
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.is_activated
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Integer isActivated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String createdTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.role.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedTimestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.id
	 * @return  the value of public.role.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.id
	 * @param id  the value for public.role.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.code
	 * @return  the value of public.role.code
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.code
	 * @param code  the value for public.role.code
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.name
	 * @return  the value of public.role.name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.name
	 * @param name  the value for public.role.name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.is_activated
	 * @return  the value of public.role.is_activated
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Integer getIsActivated() {
		return isActivated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.is_activated
	 * @param isActivated  the value for public.role.is_activated
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setIsActivated(Integer isActivated) {
		this.isActivated = isActivated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.updated_by
	 * @return  the value of public.role.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.updated_by
	 * @param updatedBy  the value for public.role.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.created_timestamp
	 * @return  the value of public.role.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getCreatedTimestamp() {
		return createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.created_timestamp
	 * @param createdTimestamp  the value for public.role.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCreatedTimestamp(String createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role.updated_timestamp
	 * @return  the value of public.role.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedTimestamp() {
		return updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role.updated_timestamp
	 * @param updatedTimestamp  the value for public.role.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedTimestamp(String updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}
}