package com.mockproject.du1.model;

import java.util.Date;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.first_name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.last_name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.dob
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date dob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.email
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.username
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.password
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.registered_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date registeredDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.activated_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date activatedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.seniority
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Integer seniority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.is_activated
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Integer isActivated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date createdTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.users.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	private Date updatedTimestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.id
	 * @return  the value of public.users.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.id
	 * @param id  the value for public.users.id
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.first_name
	 * @return  the value of public.users.first_name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.first_name
	 * @param firstName  the value for public.users.first_name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.last_name
	 * @return  the value of public.users.last_name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.last_name
	 * @param lastName  the value for public.users.last_name
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.dob
	 * @return  the value of public.users.dob
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.dob
	 * @param dob  the value for public.users.dob
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.email
	 * @return  the value of public.users.email
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.email
	 * @param email  the value for public.users.email
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.username
	 * @return  the value of public.users.username
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.username
	 * @param username  the value for public.users.username
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.password
	 * @return  the value of public.users.password
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.password
	 * @param password  the value for public.users.password
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.registered_date
	 * @return  the value of public.users.registered_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getRegisteredDate() {
		return registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.registered_date
	 * @param registeredDate  the value for public.users.registered_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setRegisteredDate(Date registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.activated_date
	 * @return  the value of public.users.activated_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getActivatedDate() {
		return activatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.activated_date
	 * @param activatedDate  the value for public.users.activated_date
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setActivatedDate(Date activatedDate) {
		this.activatedDate = activatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.seniority
	 * @return  the value of public.users.seniority
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Integer getSeniority() {
		return seniority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.seniority
	 * @param seniority  the value for public.users.seniority
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setSeniority(Integer seniority) {
		this.seniority = seniority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.is_activated
	 * @return  the value of public.users.is_activated
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Integer getIsActivated() {
		return isActivated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.is_activated
	 * @param isActivated  the value for public.users.is_activated
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setIsActivated(Integer isActivated) {
		this.isActivated = isActivated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.updated_by
	 * @return  the value of public.users.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.updated_by
	 * @param updatedBy  the value for public.users.updated_by
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.created_timestamp
	 * @return  the value of public.users.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getCreatedTimestamp() {
		return createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.created_timestamp
	 * @param createdTimestamp  the value for public.users.created_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.users.updated_timestamp
	 * @return  the value of public.users.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public Date getUpdatedTimestamp() {
		return updatedTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.users.updated_timestamp
	 * @param updatedTimestamp  the value for public.users.updated_timestamp
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	public void setUpdatedTimestamp(Date updatedTimestamp) {
		this.updatedTimestamp = updatedTimestamp;
	}
}