package com.mockproject.du1.mapper;

import com.mockproject.du1.model.CampaignCustomer;
import com.mockproject.du1.model.CampaignCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampaignCustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	long countByExample(CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByExample(CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int insert(CampaignCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int insertSelective(CampaignCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	List<CampaignCustomer> selectByExample(CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	CampaignCustomer selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") CampaignCustomer record,
			@Param("example") CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExample(@Param("record") CampaignCustomer record, @Param("example") CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKeySelective(CampaignCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.campaign_customer
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKey(CampaignCustomer record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.campaign_customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// long countByExample(CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.campaign_customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// int deleteByExample(CampaignCustomerExample example);

	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.campaign_customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// List<CampaignCustomer> selectByExample(CampaignCustomerExample example);

	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.campaign_customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// int updateByExampleSelective(@Param("record") CampaignCustomer record,
	// @Param("example") CampaignCustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.campaign_customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// int updateByExample(@Param("record") CampaignCustomer record,
	// @Param("example") CampaignCustomerExample example);

	
}