package com.mockproject.du1.mapper;

import com.mockproject.du1.model.Customer;
import com.mockproject.du1.model.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	long countByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int insert(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int insertSelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	List<Customer> selectByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	Customer selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKeySelective(Customer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 * 
	 * @mbg.generated Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKey(Customer record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// long countByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// int deleteByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// List<Customer> selectByExample(CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// int updateByExampleSelective(@Param("record") Customer record,
	// @Param("example") CustomerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.customer
	 *
	 * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
	 */
	// int updateByExample(@Param("record") Customer record, @Param("example")
	// CustomerExample example);

}