package com.mockproject.du1.mapper;

import com.mockproject.du1.model.Pages;
import com.mockproject.du1.model.PagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PagesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	long countByExample(PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByExample(PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int insert(Pages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int insertSelective(Pages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	List<Pages> selectByExample(PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	Pages selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") Pages record, @Param("example") PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExample(@Param("record") Pages record, @Param("example") PagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKeySelective(Pages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.pages
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKey(Pages record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pages
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //long countByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pages
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //int deleteByExample(PagesExample example);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pages
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //List<Pages> selectByExample(PagesExample example);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pages
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //int updateByExampleSelective(@Param("record") Pages record, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pages
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //int updateByExample(@Param("record") Pages record, @Param("example") PagesExample example);

    
}