package com.mockproject.du1.mapper;

import com.mockproject.du1.model.Users;
import com.mockproject.du1.model.UsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	long countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int insertSelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	Users selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKeySelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.users
	 * @mbg.generated  Mon Nov 04 21:55:34 ICT 2019
	 */
	int updateByPrimaryKey(Users record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //int deleteByExample(UsersExample example);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //List<Users> selectByExample(UsersExample example);

    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.users
     *
     * @mbg.generated Mon Nov 04 21:33:16 ICT 2019
     */
    //int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    
}